import React from 'react';

import { Navbar } from '~/components';

import MobileNavbar from '~/app/(user)/components/sidebar/mobile';

import { homePageItems } from '~/lib/data';

export const metadata = {
  title: 'Club Page',
  description: 'Generated by create-t3-app',
  icons: [{ rel: 'icon', url: '/favicon.ico' }],
};

const ClubsLayout = ({ children }: React.PropsWithChildren) => {
  return (
    <div className='flex flex-col'>
      <div className='hidden lg:flex'>
        <Navbar />
      </div>
      <MobileNavbar items={homePageItems} />
      <div className='py-20 lg:py-0'>{children}</div>
    </div>
  );
};

export default ClubsLayout;
