import React from 'react';

import { Navbar } from '~/components';

export const metadata = {
  title: 'Club Page',
  description: 'Generated by create-t3-app',
  icons: [{ rel: 'icon', url: '/favicon.ico' }],
};

const ClubsLayout = ({ children }: React.PropsWithChildren) => {
  return (
    <div className='flex flex-col'>
      <Navbar />
      {children}
    </div>
  );
};

export default ClubsLayout;
