import '~/styles/globals.css';
import { DashboardNavbar, Sidebar } from '../components';
import MobileNavbar from '../components/sidebar/mobile';

import { userSideNavItems as items } from '~/lib/data';

export const metadata = {
  title: 'Dashboard',
  description: 'Generated by create-t3-app',
  icons: [{ rel: 'icon', url: '/favicon.ico' }],
};

export default function DashboardLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div className='flex flex-col lg:flex-row'>
      <Sidebar items={items} />
      <MobileNavbar items={items} />
      <div className='mt-16 flex w-full flex-col lg:ml-[16rem] lg:mt-0'>
        <DashboardNavbar />
        <div className='px-3 py-6 sm:px-6 sm:py-10 md:px-12 lg:mt-16'>
          {children}
        </div>
      </div>
    </div>
  );
}
