import '~/styles/globals.css';
import { Sidebar } from '../components';
import MobileNavbar from '../components/sidebar/mobile';

export const metadata = {
  title: 'Dashboard',
  description: 'Generated by create-t3-app',
  icons: [{ rel: 'icon', url: '/favicon.ico' }],
};

export default function DashboardLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div className='flex flex-row'>
      <Sidebar />
      <MobileNavbar />
      <div className='ml-[16rem]'>{children}</div>
    </div>
  );
}
