import React from 'react';

import { Navbar } from '~/components';

import { ChakraProvider } from '@chakra-ui/react';

export const metadata = {
  title: 'Club Page',
  description: 'Generated by create-t3-app',
  icons: [{ rel: 'icon', url: '/favicon.ico' }],
};

const FormLayout = ({ children }: React.PropsWithChildren) => {
  return (
    <ChakraProvider>
      <div className='flex flex-col'>
        <Navbar />
        {children}
      </div>
    </ChakraProvider>
  );
};

export default FormLayout;
