import '~/styles/globals.css';

import { Toaster } from 'react-hot-toast';
import { ClerkProvider, ClerkLoaded, ClerkLoading } from '@clerk/nextjs';

import { GeistSans } from 'geist/font/sans';
import { PageProgress } from '~/components';
import { LoadingScreen } from '~/screens';

export const metadata = {
  title: 'Create T3 App',
  description: 'Generated by create-t3-app',
  icons: [{ rel: 'icon', url: '/favicon.ico' }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <ClerkProvider>
        <body className={`${GeistSans.className}`}>
          <PageProgress />
          <ClerkLoading>
            <LoadingScreen />
          </ClerkLoading>
          <ClerkLoaded>
            {children}
            <Toaster position='bottom-right' />
          </ClerkLoaded>
        </body>
      </ClerkProvider>
    </html>
  );
}
